const products = [
  {
    id: 1,
    title: "Delux Sheet Stand",
    category: "Sheet Stand",
    sizes: ["24x24", "30x24", "30x30", "30x36", "39x30", "39x36", "48x36"],
    image: "/images/delux-sheet-stand.jpg",
    description: "A premium quality sheet stand available in multiple sizes.",
  },
  {
    id: 2,
    title: "Square Pipe Stand",
    category: "Stand",
    sizes: [
      "15x15",
      "18x18",
      "18x24",
      "24x18",
      "24x24",
      "30x24",
      "30x30",
      "39x30",
      "39x36",
      "48x30",
      "48x36",
      "60x30",
      "60x36",
      "72x30",
      "72x36",
    ],
    image: "/images/square-pipe-stand.jpg",
    description: "Strong and durable square pipe stand for kitchen use.",
  },
  {
    id: 3,
    title: "Square Pipe Shelf Stand",
    category: "Shelf Stand",
    sizes: [
      "15x15",
      "18x18",
      "18x24",
      "24x18",
      "24x24",
      "30x24",
      "30x30",
      "39x30",
      "39x36",
      "48x36",
      "60x36",
      "72x36",
    ],
    image: "/images/square-pipe-shelf.jpg",
    description: "Multi-purpose shelf stand with a sturdy square pipe design.",
  },
  {
    id: 4,
    title: "Steps Stand",
    category: "Steps Stand",
    sizes: ["2 Steps", "3 Steps", "4 Steps"],
    image: "/images/steps-stand.jpg",
    description: "Available in 2, 3, and 4 step configurations.",
  },
  {
    id: 5,
    title: "Square Fruit Trolley",
    category: "Fruit Basket",
    sizes: ["Small", "Big"],
    image: "/images/fruit-trolley.jpg",
    description: "Multipurpose trolley for storing fruits and vegetables.",
  },
  {
    id: 6,
    title: "Round Cloth Stand",
    category: "Cloth Stand",
    sizes: ["Small", "Big"],
    image: "/images/round-cloth-stand.jpg",
    description: "Round cloth stand perfect for drying clothes.",
  },
];

export default products;
